on:
  push:
    branches: ['master']

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: lms-node-copy-node-app
      
      - name: Set environment variables
        run: |
          echo "DOCKER_IMAGE_TAGS=${{ steps.meta.outputs.tags }}" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_LABELS=${{ steps.meta.outputs.labels }}" >> $GITHUB_ENV
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE_TAGS }}
          labels: ${{ env.DOCKER_IMAGE_LABELS }}
